function H_o_sym = H_o_mf
%H_O_MF
%    H_O_SYM = H_O_MF

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Jul-2017 17:41:27

H_o_sym = [0.0,0.0,-1.0,0.0,0.0,1.0];
