function H_o_sym = H_o_mf
%H_O_MF
%    H_O_SYM = H_O_MF

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    24-Aug-2017 15:43:33

H_o_sym = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0],[3,9]);
